### PR TITLE
Tag names may contain hyphens

### PR DESCRIPTION
**Pull request by rictic**
Fixes https://github.com/textmate/html.tmbundle/issues/46

### CODE REVIEW

**Comment by rictic** [comment]
Gentle ping!

**Comment by abdonrd** [comment]
👍

**Comment by zcorpan** [comment]
They can contain hyphens but they can't start with a hyphen.

**Comment by rictic** [comment]
Updated to disallow starting with a hyphen

**Comment by zcorpan** [comment]
👍

Sorry I missed it earlier, but they also can't start with 0-9. (Maybe a separate issue, but while we're here...)

**Comment by rictic** [comment]
Sure thing. I'm not sure what's up with the `:` as I don't see anywhere in any specs where that's allowed, but by the logic of chesterton's fence I left it alone for now.

**Comment by zcorpan** [comment]
LOL I didn't even see the colon. That's not allowed as first character, either; only a-zA-Z (in HTML, that is).

**Comment by rictic** [comment]
Oh, xml namespaces. Right. Not mentioned in the HTML spec, but I guess there's still xhtml and such out there.

**Comment by infininight** [comment]
Pulled in, thanks. Added one change to ensure a word boundary on another rule.

**Pull request closed without merging**
